---
- name: Install Prerequisites
  yum:
    name:
    - epel-release
    - vim
    - wget
    - git
    - unzip
    - curl
- name: Install Nagios XI
  shell: "curl https://assets.nagios.com/downloads/nagiosxi/install.sh | sh"
  ignore_errors: true